#!/bin/sh

case $# in
1)
	file="$1"
	title="$1"
	;;
2)
	file="$1"
	title="$2"
	;;
*)
	echo "Usage: $0 <data-file> <title>"
	exit 1
esac

cat - /dev/tty <<EOF | gnuplot
set ylabel "distance (m)"
set y2label "angle (d)"
set xlabel "time (s)"
set xtics border out nomirror
set ytics border out nomirror
set y2tics border out nomirror
set title "$title"
plot "$file" using 1:3 with lines axes x1y1 title "height",\
"$file" using 1:7 with lines axes x1y1 title "speed", \
"$file" using 1:5 with lines axes x1y1 title "accel", \
"$file" using 1:13 with lines axes x1y1 title "k_speed",\
"$file" using 1:15 with lines axes x1y1 title "k_accel",\
"$file" using 1:25 with lines axes x1y2 title "angle",\
"$file" using 1:49 with lines axes x1y2 title "pyro",\
"$file" using 1:51 with lines axes x1y2 title "inhibited"
EOF
