ifndef TOPDIR
TOPDIR=..
endif

include $(TOPDIR)/lpc/Makefile-lpc.defs

LDFLAGS=$(CFLAGS) -L$(TOPDIR)/lpc -Wl,-Taltos.ld -n

ao_serial_lpc.h: $(TOPDIR)/lpc/baud_rate ao_pins.h
	nickle $(TOPDIR)/lpc/baud_rate `awk '/AO_LPC_CLKOUT/{print $$3}' ao_pins.h` > $@

ao_serial_lpc.o: ao_serial_lpc.h
