#!/bin/sh
case "$#" in
0)
	echo "usage: $0 <filename> ..."
	exit 1
	;;
esac
openocd \
	-f interface/stlink.cfg \
	-c 'transport select hla_swd' \
	-f target/stm32f1x.cfg \
	-c init \
	-c 'reset halt' \
	-c "program $1 verify reset" \
	-c 'shutdown'
