#!/bin/sh

case $# in
2)
    dev="$1"
    serial="$2"
	;;
*)
	echo "Usage: $0 <device> <serial>"
	exit 1;
	;;
esac

echo 'E 0' > $dev

while true; do

        dd if=$dev iflag=nonblock of=/dev/null > /dev/null 2>&1

	echo 'C 1' > $dev

	echo -n "Generating RF carrier. Please enter measured frequency [enter for done]: "

	read FREQ

	echo 'C 0' > $dev

	calline=`./get-radio-cal $dev`
	CURRENT_CAL=`echo $calline | awk '{print $2}'`
	CURRENT_FREQ=`echo $calline | awk '{print $4}'`
	CAL_VALUE=$CURRENT_CAL

	case "$FREQ" in
	"")
		echo $serial","$CAL_VALUE >> cal_values
		exit 0
		;;
	*)
		echo "Current radio calibration "$CURRENT_CAL
		echo "Current radio frequency "$CURRENT_FREQ

		CAL_VALUE=`nickle -e "floor($CURRENT_FREQ / $FREQ * $CURRENT_CAL + 0.5)"`

		echo "Setting cal value" $CAL_VALUE

		dd if=$dev iflag=nonblock of=/dev/null > /dev/null 2>&1

		cat << EOF > $dev
c f $CAL_VALUE
EOF
		;;
	esac
done

