#!/bin/sh

dev="$1"
shift

for igniter in "$@"; do
	pass="n"
	while [ $pass != "y" ]; do
		echo -n "Testing $igniter igniter. Press enter to continue..."
		read foo < /dev/tty
		../ao-tools/ao-test-igniter/ao-test-igniter --tty="$dev" $igniter

		case $? in
		    0)
			echo "pass"
			pass="y"
			;;
		    *)
			echo "Failed. Try again."
			;;
		esac
	done
done

exit 0
