#!/bin/sh

VERSION=3.0
PRODUCT=TeleGPS
BASE=`echo $PRODUCT | tr 'A-Z' 'a-z'`

echo "$PRODUCT-v$VERSION Test Program"
echo "Copyright 2023 by Bdale Garbee.  Released under GPL v3"
echo
echo "Expectations:"
echo "\t$PRODUCT v$VERSION powered from USB"
echo

ret=1
ao-list | while read product serial dev; do
    case "$product" in
	"$PRODUCT-v$VERSION")

	    echo "Testing $product $serial $dev"

	    FLASHSIZE=2097152

	    echo "Testing flash"
	    ao-test-flash --tty="$dev" "$FLASHSIZE"

	    case $? in
		0)
		    ;;
		*)
		    echo "failed"
		    exit 1
	    esac

	    echo "Testing GPS"
	    ao-test-gps --tty="$dev"

	    case $? in
		0)
		    ;;
		*)
		    echo "failed"
		    exit 1
	    esac

	    echo "$PRODUCT-v$VERSION" serial "$serial" is ready to ship
            echo "\007"
	    ret=0
	    ;;
	*)
	    echo "Skipping $product $serial $dev"
	    ;;
    esac
done
