#!/bin/sh

if [ -x ../ao-tools/ao-flash/ao-flash-lpc ]; then
	FLASH_LPC=../ao-tools/ao-flash/ao-flash-lpc
elif [ -x /usr/bin/ao-flash-lpc ]; then
	FLASH_LPC=/usr/bin/ao-flash-lpc
else
	echo "Can't find ao-flash-lpc!  Aborting."
	exit 1
fi

if [ -x /usr/bin/ao-usbload ]; then
	USBLOAD=/usr/bin/ao-usbload
else
	echo "Can't find ao-usbload!  Aborting."
	exit 1
fi

PRODUCT=teledongle
PRODUCT_NAME=TeleDongle
VERSION=3.0

echo "$PRODUCT_NAME v$VERSION Turn-On and Calibration Program"
echo "Copyright © 2015 by Bdale Garbee.  Released under GPL v2"
echo
echo "Expectations:"
echo "\t$PRODUCT_NAME v$VERSION powered from USB"
echo "\t\twith ST-Link-V2 cabled to debug header"
echo "\t\twith coax from UHF to frequency counter"
echo
echo -n "$PRODUCT_NAME-$VERSION serial number: "
read SERIAL

BINARIES=$HOME/altusmetrumllc/Binaries

LOADER="$BINARIES/loaders/$PRODUCT-v$VERSION-"*.elf
ALTOS="$BINARIES/$PRODUCT-v$VERSION"*.elf

$FLASH_LPC $LOADER || exit 1

sleep 2

$USBLOAD --serial=$SERIAL $ALTOS || exit 1

sleep 5

dev=`ao-list | awk '/TeleDongle-v'"$VERSION"'/ { print $3; exit(0); }'`

case "$dev" in
/dev/tty*)
	echo "TeleDongle found on $dev"
	;;
*)
	echo 'No TeleDongle-v'"$VERSION"' found'
	exit 1
	;;
esac

echo 'E 0' > $dev

./cal-freq-file $dev $SERIAL

case $? in
    0)
	;;
    *)
	echo "Frequency calibration failed"
	exit 1
	;;
esac

CAL_VALUE=`grep "^$SERIAL," cal_values | tail -1 | sed 's/^[^,]*,//'`

case "$CAL_VALUE" in
    [1-9]*)
    ;;
    *)
	echo "Invalid calibration value: $CAL_VALUE"
	exit 1
	;;
esac

echo "Reflashing with calibration: $CAL_VALUE"

$USBLOAD --cal=$CAL_VALUE --tty=$dev $ALTOS || exit 1

echo "$PRODUCT_NAME-v$VERSION $SERIAL is ready to ship"

exit $?
