= Release Notes for Version 1.9.18
include::release-head.adoc[]
:doctype: article

	Version 1.9.18

	== AltOS
	
	* Add support for EasyTimer V2. The new version of this
          product has on-board storage to log data during flight.

	== AltosUI & TeleGPS application

	* Add support for EasyTimer V2. This includes support for
          analyizing flight data from the on-board logs.

	* Allow on-board beepers to be disabled by setting the
	  frequency to 0.
