= Release Notes for Version 1.9.3
include::release-head.adoc[]
:doctype: article

	Version 1.9.3

	== AltOS

	* Add APRS offset

	* Fix max log size

	* Check flight erasing more carefully. Handle interrupting erasing in the
	  middle.

	* Add EasyTimer support

	== AltosUI, TeleGPS, MicroPeak

	* Add configuration support for APRS offset

	* Adjust flight log sizes to account for erase block size