= Release Notes for Version 1.8.7
:toc!:
:doctype: article

	Version 1.8.7

	== AltOS

	* Include TeleMega v3.0 firmware
	
	== AltosUI, TeleGPS

	* Poll for new devices while Device dialog is displayed

	* Wait for device to re-appear when flashing new firmware

	* Fetch correct TeleBT v4.0 RF calibration values from web
          site when reflashing.

	* Change gyro headings in .csv files from x/y/z to
          roll/pitch/yaw

	* Add documentation about Packet Link mode

	* Add documentation about forcing TeleMini RF parameters to
          known values.

	* Create a proxy server for Google Maps to re-enable map images

	== MicroPeak

	* Poll for new devices while Device dialog is displayed

	
