[appendix]
== Release Notes

	:leveloffset: 2
	include::release-notes-1.6.3.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.5.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.3.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.3.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.3.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.2.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.1.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.0.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-0.9.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-0.9.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-0.8.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-0.7.1.raw[]

	:leveloffset: 0
