= Release Notes for Version 1.9.11
include::release-head.adoc[]
:doctype: article

	Version 1.9.11

	== AltOS

	* Make Apogee Delay work again.

	* Allow TX power to be limited to 10mW for compliance with
          some uses under UK regulations.

	* Fix numerous minor issues with 16- vs 32- bit time values.

	== AltosUI

	* Support M1-based Macs, follow AdoptOpenJDK to Adoptium

	== AltosDroid

	* Handle Bluetooth permissions reliably.

	* Fix some screen rotation bugs.
