[appendix]
== Release Notes

	:leveloffset: 2
	include::release-notes-1.8.6.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.5.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.4.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.3.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.8.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.7.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.8.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.5.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.4.raw[]

	:leveloffset: 2
	include::release-notes-1.6.3.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.6.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.5.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.2.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.1.raw[]

	<<<<
	:leveloffset: 2
	include::release-notes-1.4.raw[]
