== TeleGPS Quick Start Guide

	TeleGPS is designed to be easy to use. Requiring no external
	components, flying takes just a few steps.

	First, download and install the software from
	http://altusmetrum.org/AltOS. This will make sure that
	you have the right device drivers installed.

	Next, plug in the battery and USB cable and connect TeleGPS to
	your computer. This will charge the battery and allow you to
	configure the device.

	Start the TeleGPS application and set the callsign and frequency
	on your TeleGPS device; refer to the Configure TeleGPS section
	in the TeleGPS Application chapter for instructions.

	Unplug TeleGPS when the battery charger light goes green. This
	will enable the radio and logging portions of the TeleGPS
	firmware.

	Connect TeleDongle to your computer and start TeleGPS or start
	AltosDroid on your android device and connect to TeleBT. Set the
	frequency to match the TeleGPS and you should be receiving telemetry.
