Document: altos
Title: Debian altos Manual
Author: <insert document author here>
Abstract: This manual describes what altos is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/altos/altos.sgml.gz

Format: postscript
Files: /usr/share/doc/altos/altos.ps.gz

Format: text
Files: /usr/share/doc/altos/altos.text.gz

Format: HTML
Index: /usr/share/doc/altos/html/index.html
Files: /usr/share/doc/altos/html/*.html
