ifndef TOPDIR
TOPDIR=..
endif

include $(TOPDIR)/stmf0/Makefile-stmf0.defs

LOADER=flash-loader/$(PROGNAME)-altos-flash-$(VERSION).elf
MAKEBIN=$(TOPDIR)/../ao-tools/ao-makebin/ao-makebin
FLASH_ADDR=0x08000000

LDFLAGS=$(CFLAGS) -L$(TOPDIR)/stmf0 -Wl,-Taltos.ld -n

.DEFAULT_GOAL=all
