#!/bin/sh
dir=`dirname "$0"`
cd "$dir"
mkdir -p ~/Applications/AltOS
find ~/Applications/AltOS -type d -print0 | xargs -0 chmod +w
cp -f -a * ~/Applications/AltOS
cd ~/Applications/AltOS
chmod +w *
xattr -c *
