#!/bin/bash

case `id -u` in
    0)
    ;;
    *)
	# Check for java
	if [ ! -d /Library/Java/JavaVirtualMachines/ -o `ls /Library/Java/JavaVirtualMachine` == '' ]; then
	    open https://adoptopenjdk.net/
	    osascript -e 'display dialog "Install Java from https://adoptopenjdk.net then click OK" buttons {"Continue"}'
	fi
	sudo "$0" "$@"
	;;
esac

dir=`dirname "$0"`
cd "$dir"
APP=`echo *.app`
LIBRARY=/Library/AltusMetrum
APPLICATIONS=/Applications/
for file in *; do
    case "$i" in
	*.app)
	    mkdir -p "$(APPLICATIONS)"
	    if [ -d "$(APPLICATIONS)/$(APP)/." ]; then
		rm -rf "$(APPLICATIONS)/$(APP)"
	    fi
	    cp -a "$i" "$(APPLICATIONS)/$(APP)"
	    chmod +w "$(APPLICATIONS)/$(APP)"/*
	    xattr -c "$(APPLICATIONS)/$(APP)"/*
	    ;;
	*)
	    mkdir -p "$(LIBRARY)"
	    cp -a "$i" "$(LIBRARY)"
	    ;;
    esac
done
